namespace WsUtaSystem.Application.DTOs.Guards;

public record GuardShiftPlanningDto(
    int PlanningId,
    int EmployeeId,
    string EmployeeFullName,
    string? EmployeeIdCard,
    int? GroupId,
    string? GroupName,
    int LocationId,
    string LocationName,
    string? LocationCode,
    DateOnly WorkDate,
    int ScheduleId,
    string ScheduleDescription,
    string? ScheduleCode,
    string PlanningSource,
    string Status,
    bool IsAutoGenerated,
    bool IsActiveForAssignment,
    string? Notes,
    bool HasActiveReplacement,
    int? ActiveReplacementEmployeeId,
    string? ActiveReplacementEmployeeName
);

public record CreateGuardShiftPlanningDto(
    int EmployeeId,
    int? GroupId,
    int LocationId,
    DateOnly WorkDate,
    int ScheduleId,
    int PlanningSourceTypeId,
    int StatusTypeId,
    string? Notes
);

public record GenerateGuardShiftPlanningRequestDto(
    int GroupId,
    DateOnly StartDate,
    DateOnly EndDate,
    int LocationId,
    bool OverwriteExisting
);

public record GuardShiftCalendarFilterDto(
    DateOnly StartDate,
    DateOnly EndDate,
    int? GroupId,
    int? LocationId,
    int? RootLocationId,
    int? EmployeeId,
    string? Status
);

public record GuardShiftCalendarItemDto(
    DateOnly WorkDate,
    int PlanningId,
    int EmployeeId,
    string EmployeeFullName,
    int LocationId,
    string LocationName,
    int ScheduleId,
    string ScheduleDescription,
    string? ScheduleCode,
    string Status,
    bool HasReplacement,
    bool HasPermissionConflict,
    bool HasVacationConflict,
    bool HasValidationWarning
);

public record GuardShiftPlanningResultDto(
    int Generated,
    int Skipped,
    int Errors,
    List<string> Messages
);

public record UpdateGuardShiftPlanningStatusDto(
    int StatusTypeId,
    string? Notes
);

// ─── Cancelación de planificación ────────────────────────────────────────────
// No borra filas: marca IsActiveForAssignment=false (mismo flag que ya usa
// GenerateAsync al sobrescribir con OverwriteExisting), por lo que el chequeo
// de "ya está planificado" (HasActiveShiftOnDateAsync) libera la fecha
// automáticamente sin tocar esa lógica.

public record CancelGuardShiftPlanningDto(
    string? Notes
);

// GroupId null = cancela todos los grupos en el rango de fechas indicado.
public record CancelGuardShiftPlanningRangeDto(
    int? GroupId,
    DateOnly StartDate,
    DateOnly EndDate,
    string? Notes
);

public record CancelGuardShiftPlanningResultDto(
    int Cancelled,
    List<string> Messages
);

// ─── Generación Preview / Confirm ───────────────────────────────────────────

public record GeneratePreviewRequestDto(
    DateOnly StartDate,
    DateOnly EndDate,
    int? LocationId,
    int? GroupId,
    int? EmployeeId,
    string Mode,             // ALL_GROUPS | BY_LOCATION | BY_GROUP | BY_EMPLOYEE
    bool IncludeRestDays,
    string RegenerateMode    // SKIP_EXISTING | CANCEL_AND_RECREATE
);

public record GeneratePreviewItemDto(
    int EmployeeId,
    string EmployeeFullName,
    int GroupId,
    string GroupName,
    int? LocationId,
    string? LocationName,
    DateOnly WorkDate,
    int ScheduleId,
    string? ScheduleCode,
    string ScheduleName,
    int CycleDay,
    bool WillSkip,
    bool HasConflict,
    string? ConflictType,
    string? ConflictMessage,
    bool IsValid,
    bool IsRestDay
);

public record GeneratePreviewResponseDto(
    int TotalToGenerate,
    int RestDaysCalculated,
    int WillSkip,
    int Conflicts,
    int PermissionConflicts,
    int VacationConflicts,
    int DoubleShiftConflicts,
    int OverlapConflicts,
    int MissingLocation,
    List<GeneratePreviewItemDto> Items
);

// ─── Schedule Board ──────────────────────────────────────────────────────────

public record ScheduleBoardFilterDto(
    DateOnly StartDate,
    DateOnly EndDate,
    int? LocationId,
    int? GroupId,
    int? EmployeeId,
    string? ScheduleCode,
    string? Status,
    string ViewMode          // BY_LOCATION | BY_GUARD | BY_GROUP
);

public record ScheduleBoardCellEmployeeDto(
    int EmployeeId,
    string FullName,
    bool IsReplacement,
    int PlanningId,
    int? GroupId,
    string? GroupName,
    string? GroupColorCode
);

public record ScheduleBoardCellDto(
    DateOnly Date,
    int? PlanningId,
    List<ScheduleBoardCellEmployeeDto> Employees,
    string Status,
    bool HasConflict,
    bool HasReplacement,
    bool HasPermission,
    bool HasVacation
);

public record ScheduleBoardRowDto(
    string RowKey,
    int LocationId,
    string LocationName,
    string? LocationCode,
    int? ParentLocationId,
    string? ParentLocationName,
    string ScheduleCode,
    string ScheduleName,
    List<ScheduleBoardCellDto> Cells
);

public record ScheduleBoardResponseDto(
    List<DateOnly> Dates,
    List<ScheduleBoardRowDto> Rows
);

// ─── Detalle de planificación (panel lateral) ────────────────────────────────

public record GuardShiftPlanningDetailDto(
    int PlanningId,
    DateOnly WorkDate,
    int LocationId,
    string LocationName,
    string? LocationCode,
    int? GroupId,
    string? GroupName,
    int? PatternId,
    string? PatternCode,
    string? PatternSequence,
    int? CycleDay,
    int ScheduleId,
    string? ScheduleCode,
    string ScheduleName,
    int EmployeeId,
    string EmployeeFullName,
    string? EmployeeIdCard,
    string Status,
    bool IsAutoGenerated,
    string? Notes,
    bool HasActiveReplacement,
    int? ActiveReplacementEmployeeId,
    string? ActiveReplacementEmployeeName,
    List<GuardAssignmentValidationDto> Validations,
    List<GuardShiftChangeDto> Changes
);
