using WsUtaSystem.Application.Interfaces.Auditable;

namespace WsUtaSystem.Models.Guards;

public class GuardShiftPlanning : IAuditable
{
    public int PlanningId { get; set; }
    public int EmployeeId { get; set; }
    public int? GroupId { get; set; }
    public int LocationId { get; set; }
    public DateOnly WorkDate { get; set; }
    public int ScheduleId { get; set; }
    public int PlanningSourceTypeId { get; set; }
    public int StatusTypeId { get; set; }
    public bool IsAutoGenerated { get; set; } = true;
    public bool IsActiveForAssignment { get; set; } = true;
    public bool AllowDoubleShift { get; set; }
    public string? Notes { get; set; }
    // Snapshot al momento de crear el turno — para que las vistas históricas no cambien
    // retroactivamente si el grupo/empleado/horario se edita después. NULL en filas creadas
    // antes de este campo; el mapeo hace fallback al dato en vivo en ese caso.
    public string? GroupNameSnapshot { get; set; }
    public string? GroupColorSnapshot { get; set; }
    public string? EmployeeNameSnapshot { get; set; }
    public string? ScheduleCodeSnapshot { get; set; }
    public string? ScheduleDescriptionSnapshot { get; set; }
    public int? CreatedBy { get; set; }
    public DateTime? CreatedAt { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public byte[]? RowVersion { get; set; }

    public virtual Employees? Employee { get; set; }
    public virtual GuardRotationGroup? Group { get; set; }
    public virtual GuardServiceLocation? Location { get; set; }
    public virtual Schedules? Schedule { get; set; }
    public virtual RefTypes? PlanningSourceType { get; set; }
    public virtual RefTypes? StatusType { get; set; }
    public virtual ICollection<GuardShiftChange> Changes { get; set; } = new List<GuardShiftChange>();
    public virtual ICollection<GuardAssignmentValidation> Validations { get; set; } = new List<GuardAssignmentValidation>();
}
