using Microsoft.EntityFrameworkCore;
using WsUtaSystem.Application.Common.Interfaces;
using WsUtaSystem.Application.DTOs.Guards;
using WsUtaSystem.Application.Interfaces.Guards;
using WsUtaSystem.Data;
using WsUtaSystem.Models;
using WsUtaSystem.Models.Guards;

namespace WsUtaSystem.Application.Services.Guards;

public class GuardShiftPlanningService : IGuardShiftPlanningService
{
    private readonly IGuardShiftPlanningRepository _repo;
    private readonly IGuardAssignmentValidationService _validationService;
    private readonly IEmployeeAvailabilityService _availabilityService;
    private readonly IGuardRotationGroupRepository _groupRepo;
    private readonly IRotationPatternRepository _patternRepo;
    private readonly AppDbContext _db;
    private readonly ICurrentUserService _currentUser;

    public GuardShiftPlanningService(
        IGuardShiftPlanningRepository repo,
        IGuardAssignmentValidationService validationService,
        IEmployeeAvailabilityService availabilityService,
        IGuardRotationGroupRepository groupRepo,
        IRotationPatternRepository patternRepo,
        AppDbContext db,
        ICurrentUserService currentUser)
    {
        _repo = repo;
        _validationService = validationService;
        _availabilityService = availabilityService;
        _groupRepo = groupRepo;
        _patternRepo = patternRepo;
        _db = db;
        _currentUser = currentUser;
    }

    public async Task<List<GuardShiftCalendarItemDto>> GetCalendarAsync(GuardShiftCalendarFilterDto filter, CancellationToken ct)
    {
        var plannings = await _repo.GetCalendarAsync(filter, ct);

        return plannings.Select(p =>
        {
            var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
            return new GuardShiftCalendarItemDto(
                p.WorkDate, p.PlanningId, p.EmployeeId,
                $"{p.Employee?.People?.FirstName} {p.Employee?.People?.LastName}",
                p.LocationId, p.Location?.LocationName ?? "",
                p.ScheduleId, p.Schedule?.Description ?? "",
                p.Schedule?.ScheduleCode,
                p.StatusType?.Name ?? "",
                activeChange is not null,
                false, false, false
            );
        }).ToList();
    }

    public async Task<GuardShiftPlanningDto?> GetByIdAsync(int planningId, CancellationToken ct)
    {
        var p = await _repo.GetWithChangesAsync(planningId, ct);
        if (p is null) return null;
        return MapToDto(p);
    }

    public async Task<GuardShiftPlanningDto> CreateAsync(CreateGuardShiftPlanningDto dto, CancellationToken ct)
    {
        var validateReq = new ValidateGuardAssignmentRequestDto(
            dto.EmployeeId, dto.LocationId, dto.WorkDate, dto.ScheduleId, null, false);
        var validation = await _validationService.ValidateAsync(validateReq, ct);

        if (validation.HasBlockingErrors)
            throw new InvalidOperationException(
                "No se puede crear la planificación: " +
                string.Join("; ", validation.Validations.Where(v => v.Severity == "BLOCKING").Select(v => v.Message)));

        var entity = new GuardShiftPlanning
        {
            EmployeeId = dto.EmployeeId,
            GroupId = dto.GroupId,
            LocationId = dto.LocationId,
            WorkDate = dto.WorkDate,
            ScheduleId = dto.ScheduleId,
            PlanningSourceTypeId = dto.PlanningSourceTypeId,
            StatusTypeId = dto.StatusTypeId,
            IsAutoGenerated = false,
            IsActiveForAssignment = true,
            Notes = dto.Notes
        };
        await _db.GuardShiftPlannings.AddAsync(entity, ct);
        await _db.SaveChangesAsync(ct);
        return MapToDto(entity);
    }

    public async Task<GuardShiftPlanningResultDto> GenerateAsync(GenerateGuardShiftPlanningRequestDto dto, CancellationToken ct)
    {
        var group = await _groupRepo.GetWithEmployeesAsync(dto.GroupId, ct)
            ?? throw new KeyNotFoundException($"Grupo {dto.GroupId} no encontrado.");

        var groupPattern = await _db.GuardGroupRotationPatterns
            .Where(gp => gp.GroupId == dto.GroupId && gp.IsActive
                && gp.ValidFrom <= dto.StartDate
                && (gp.ValidTo == null || gp.ValidTo >= dto.StartDate))
            .OrderByDescending(gp => gp.ValidFrom)
            .FirstOrDefaultAsync(ct)
            ?? throw new InvalidOperationException($"El grupo {dto.GroupId} no tiene patrón de rotación activo para la fecha indicada.");

        var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct)
            ?? throw new KeyNotFoundException($"Patrón {groupPattern.PatternId} no encontrado.");

        var sourceTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_SOURCE" && r.Name == "AUTO")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        var statusTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_STATUS" && r.Name == "PLANNED")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        int generated = 0, skipped = 0, errors = 0;
        var messages = new List<string>();
        var activeEmployees = await _groupRepo.GetActiveEmployeesAsync(dto.GroupId, dto.StartDate, ct);

        for (var date = dto.StartDate; date <= dto.EndDate; date = date.AddDays(1))
        {
            int cycleDay = ((date.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays;
            var patternDetail = pattern.Details.FirstOrDefault(d => d.DayOrder == cycleDay + 1);
            if (patternDetail is null || patternDetail.IsRestDay) continue;

            foreach (var groupEmp in activeEmployees)
            {
                try
                {
                    var hasShift = await _repo.HasActiveShiftOnDateAsync(groupEmp.EmployeeId, date, null, ct);
                    if (hasShift)
                    {
                        if (!dto.OverwriteExisting) { skipped++; continue; }
                        var existing = await _db.GuardShiftPlannings
                            .FirstAsync(p => p.EmployeeId == groupEmp.EmployeeId && p.WorkDate == date && p.IsActiveForAssignment, ct);
                        existing.IsActiveForAssignment = false;
                    }

                    var planning = new GuardShiftPlanning
                    {
                        EmployeeId = groupEmp.EmployeeId,
                        GroupId = dto.GroupId,
                        LocationId = dto.LocationId,
                        WorkDate = date,
                        ScheduleId = patternDetail.ScheduleId!.Value,
                        PlanningSourceTypeId = sourceTypeId,
                        StatusTypeId = statusTypeId,
                        IsAutoGenerated = true,
                        IsActiveForAssignment = true
                    };

                    await _db.GuardShiftPlannings.AddAsync(planning, ct);
                    generated++;
                }
                catch (Exception ex)
                {
                    errors++;
                    messages.Add($"Error en empleado {groupEmp.EmployeeId} fecha {date}: {ex.Message}");
                }
            }
        }

        await _db.SaveChangesAsync(ct);
        messages.Insert(0, $"Generación completada: {generated} creados, {skipped} omitidos, {errors} errores.");
        return new GuardShiftPlanningResultDto(generated, skipped, errors, messages);
    }

    public async Task<GuardShiftPlanningDetailDto?> GetPlanningDetailAsync(int planningId, CancellationToken ct)
    {
        var p = await _db.GuardShiftPlannings
            .Include(x => x.Employee).ThenInclude(e => e!.People)
            .Include(x => x.Location)
            .Include(x => x.Schedule)
            .Include(x => x.StatusType)
            .Include(x => x.Changes).ThenInclude(c => c.ReplacementEmployee).ThenInclude(e => e!.People)
            .Include(x => x.Changes).ThenInclude(c => c.OriginalSchedule)
            .Include(x => x.Changes).ThenInclude(c => c.NewSchedule)
            .Include(x => x.Changes).ThenInclude(c => c.ChangeType)
            .Include(x => x.Changes).ThenInclude(c => c.StatusType)
            .Include(x => x.Validations).ThenInclude(v => v.ValidationType)
            .Include(x => x.Validations).ThenInclude(v => v.ResultType)
            .Include(x => x.Validations).ThenInclude(v => v.SeverityType)
            .FirstOrDefaultAsync(x => x.PlanningId == planningId, ct);

        if (p is null) return null;

        // Resolver patrón del grupo para calcular día de ciclo
        int? cycleDay = null;
        int? patternId = null;
        string? patternCode = null;
        string? patternSequence = null;

        if (p.GroupId.HasValue)
        {
            var groupPattern = await _db.GuardGroupRotationPatterns
                .Where(gp => gp.GroupId == p.GroupId && gp.IsActive
                    && gp.ValidFrom <= p.WorkDate
                    && (gp.ValidTo == null || gp.ValidTo >= p.WorkDate))
                .OrderByDescending(gp => gp.ValidFrom)
                .FirstOrDefaultAsync(ct);

            if (groupPattern is not null)
            {
                patternId = groupPattern.PatternId;
                var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct);
                if (pattern is not null)
                {
                    patternCode = pattern.PatternCode;
                    cycleDay = ((p.WorkDate.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays + 1;
                    patternSequence = string.Join("", pattern.Details
                        .OrderBy(d => d.DayOrder)
                        .Select(d => d.IsRestDay ? "L" : (d.Schedule?.ScheduleCode?.Substring(0, 1) ?? "?")));
                }
            }
        }

        var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
        var validations = p.Validations.Select(v => new GuardAssignmentValidationDto(
            v.ValidationId, v.EmployeeId,
            $"{p.Employee?.People?.FirstName} {p.Employee?.People?.LastName}",
            v.PlanningId, v.ShiftChangeId,
            v.ValidationType?.Name ?? "", v.ResultType?.Name ?? "", v.SeverityType?.Name ?? "",
            v.ValidationDate, v.Message, v.Details
        )).ToList();

        var changes = p.Changes.Select(MapChangeToDto).ToList();

        return new GuardShiftPlanningDetailDto(
            p.PlanningId, p.WorkDate,
            p.LocationId, p.Location?.LocationName ?? "", p.Location?.LocationCode,
            p.GroupId, null,
            patternId, patternCode, patternSequence, cycleDay,
            p.ScheduleId, p.Schedule?.ScheduleCode, p.Schedule?.Description ?? "",
            p.EmployeeId, $"{p.Employee?.People?.FirstName} {p.Employee?.People?.LastName}", p.Employee?.People?.IdCard,
            p.StatusType?.Name ?? "", p.IsAutoGenerated, p.Notes,
            activeChange is not null,
            activeChange?.ReplacementEmployeeId,
            activeChange is not null ? $"{activeChange.ReplacementEmployee?.People?.FirstName} {activeChange.ReplacementEmployee?.People?.LastName}" : null,
            validations, changes
        );
    }

    public async Task<GeneratePreviewResponseDto> GeneratePreviewAsync(GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var (items, restDays) = await RunGenerationLogicAsync(dto, dryRun: true, ct);
        return BuildPreviewResponse(items, restDays);
    }

    public async Task<GuardShiftPlanningResultDto> GenerateConfirmAsync(GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var (items, _) = await RunGenerationLogicAsync(dto, dryRun: false, ct);
        await _db.SaveChangesAsync(ct);

        var generated = items.Count(i => i.IsValid && !i.WillSkip);
        var skipped   = items.Count(i => i.WillSkip);
        var errors    = items.Count(i => i.HasConflict);

        var messages = new List<string> { $"Generación confirmada: {generated} creados, {skipped} omitidos, {errors} conflictos." };
        foreach (var conflict in items.Where(i => i.HasConflict).Take(20))
            messages.Add($"  Conflicto [{conflict.ConflictType}] {conflict.EmployeeFullName} {conflict.WorkDate:dd/MM/yyyy}: {conflict.ConflictMessage}");

        return new GuardShiftPlanningResultDto(generated, skipped, errors, messages);
    }

    public async Task<ScheduleBoardResponseDto> GetScheduleBoardAsync(ScheduleBoardFilterDto filter, CancellationToken ct)
    {
        var query = _db.GuardShiftPlannings
            .Include(p => p.Employee).ThenInclude(e => e!.People)
            .Include(p => p.Location)
            .Include(p => p.Schedule)
            .Include(p => p.StatusType)
            .Include(p => p.Changes.Where(c => c.IsActiveForAttendance))
            .Where(p => p.WorkDate >= filter.StartDate
                     && p.WorkDate <= filter.EndDate
                     && p.IsActiveForAssignment);

        if (filter.LocationId.HasValue)     query = query.Where(p => p.LocationId == filter.LocationId);
        if (filter.GroupId.HasValue)        query = query.Where(p => p.GroupId == filter.GroupId);
        if (filter.EmployeeId.HasValue)     query = query.Where(p => p.EmployeeId == filter.EmployeeId);
        if (!string.IsNullOrEmpty(filter.Status))       query = query.Where(p => p.StatusType!.Name == filter.Status);
        if (!string.IsNullOrEmpty(filter.ScheduleCode)) query = query.Where(p => p.Schedule!.ScheduleCode == filter.ScheduleCode);

        var plannings = await query.ToListAsync(ct);

        var dates = new List<DateOnly>();
        for (var d = filter.StartDate; d <= filter.EndDate; d = d.AddDays(1))
            dates.Add(d);

        var rowGroups = plannings
            .GroupBy(p => new { p.LocationId, ScheduleCode = p.Schedule?.ScheduleCode ?? "" })
            .OrderBy(g => g.First().Location?.LocationName ?? "")
            .ThenBy(g => g.Key.ScheduleCode);

        var rows = rowGroups.Select(group =>
        {
            var sample = group.First();
            var rowKey = $"{sample.Location?.LocationCode ?? sample.LocationId.ToString()}_{sample.Schedule?.ScheduleCode ?? "X"}";

            var cells = dates.Select(date =>
            {
                var dayPlannings = group.Where(p => p.WorkDate == date).ToList();
                var employees = dayPlannings.Select(p =>
                {
                    var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
                    return new ScheduleBoardCellEmployeeDto(
                        p.EmployeeId,
                        $"{p.Employee?.People?.FirstName} {p.Employee?.People?.LastName}",
                        activeChange is not null,
                        p.PlanningId
                    );
                }).ToList();

                var cellStatus = dayPlannings.Count == 0 ? "UNCOVERED" : (sample.StatusType?.Name ?? "PLANNED");

                return new ScheduleBoardCellDto(
                    date, dayPlannings.FirstOrDefault()?.PlanningId,
                    employees, cellStatus,
                    false, employees.Any(e => e.IsReplacement), false, false
                );
            }).ToList();

            return new ScheduleBoardRowDto(
                rowKey, sample.LocationId,
                sample.Location?.LocationName ?? "", sample.Location?.LocationCode,
                sample.Schedule?.ScheduleCode ?? "", sample.Schedule?.Description ?? "",
                cells
            );
        }).ToList();

        return new ScheduleBoardResponseDto(dates, rows);
    }

    public async Task<ValidateGuardAssignmentResultDto> ValidateAssignmentAsync(ValidateGuardAssignmentRequestDto dto, CancellationToken ct) =>
        await _validationService.ValidateAsync(dto, ct);

    public async Task<GuardDashboardDto> GetDashboardAsync(CancellationToken ct)
    {
        var today = DateOnly.FromDateTime(DateTime.Today);
        var filter = new GuardShiftCalendarFilterDto(today, today, null, null, null, null, null);
        var todayShifts = await GetCalendarAsync(filter, ct);

        var pendingChanges = await _db.GuardShiftChanges
            .Include(c => c.Planning).ThenInclude(p => p!.Location)
            .Include(c => c.OriginalEmployee).ThenInclude(e => e!.People)
            .Include(c => c.ReplacementEmployee).ThenInclude(e => e!.People)
            .Include(c => c.StatusType)
            .Where(c => c.StatusType!.Name == "PENDING")
            .ToListAsync(ct);

        var pendingDtos = pendingChanges.Select(MapChangeToDto).ToList();

        return new GuardDashboardDto(
            todayShifts.Count,
            0,
            pendingDtos.Count,
            0,
            0,
            todayShifts,
            pendingDtos
        );
    }

    private static GuardShiftPlanningDto MapToDto(GuardShiftPlanning p)
    {
        var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
        return new GuardShiftPlanningDto(
            p.PlanningId, p.EmployeeId,
            $"{p.Employee?.People?.FirstName} {p.Employee?.People?.LastName}",
            p.Employee?.People?.IdCard,
            p.GroupId, p.Group?.Name, p.LocationId, p.Location?.LocationName ?? "",
            p.Location?.LocationCode, p.WorkDate, p.ScheduleId,
            p.Schedule?.Description ?? "", p.Schedule?.ScheduleCode,
            p.PlanningSourceType?.Name ?? "", p.StatusType?.Name ?? "",
            p.IsAutoGenerated, p.IsActiveForAssignment, p.Notes,
            activeChange is not null,
            activeChange?.ReplacementEmployeeId,
            activeChange is not null ? $"{activeChange.ReplacementEmployee?.People?.FirstName} {activeChange.ReplacementEmployee?.People?.LastName}" : null
        );
    }

    private static GuardShiftChangeDto MapChangeToDto(GuardShiftChange c) =>
        new(c.ShiftChangeId, c.PlanningId,
            c.Planning?.WorkDate ?? default,
            c.OriginalEmployeeId,
            $"{c.OriginalEmployee?.People?.FirstName} {c.OriginalEmployee?.People?.LastName}",
            c.ReplacementEmployeeId,
            c.ReplacementEmployee is null ? null : $"{c.ReplacementEmployee.People?.FirstName} {c.ReplacementEmployee.People?.LastName}",
            c.OriginalScheduleId, c.OriginalSchedule?.Description ?? "",
            c.NewScheduleId, c.NewSchedule?.Description,
            c.ChangeType?.Name ?? "", c.StatusType?.Name ?? "",
            c.IsActiveForAttendance, c.Reason, c.RequestedAt, c.RequestedBy, null,
            c.ApprovedBy, null, c.ApprovedAt, c.RejectionReason);

    // ─── Helpers de generación ──────────────────────────────────────────────

    private async Task<(List<GeneratePreviewItemDto> items, int restDays)> RunGenerationLogicAsync(
        GeneratePreviewRequestDto dto, bool dryRun, CancellationToken ct)
    {
        var groups = await ResolveGroupsAsync(dto, ct);
        var items = new List<GeneratePreviewItemDto>();
        int restDays = 0;

        var sourceTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_SOURCE" && r.Name == "AUTO")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        var statusTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_STATUS" && r.Name == "PLANNED")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        // Precargar horarios para eficiencia
        var scheduleMap = await _db.Schedules
            .ToDictionaryAsync(s => s.ScheduleId, s => s, ct);

        // Precargar nombre de ubicación si se proporcionó
        string? locationName = null;
        if (dto.LocationId.HasValue)
        {
            locationName = await _db.Set<WsUtaSystem.Models.Guards.GuardServiceLocation>()
                .Where(l => l.LocationId == dto.LocationId)
                .Select(l => l.LocationName)
                .FirstOrDefaultAsync(ct);
        }

        foreach (var group in groups)
        {
            var groupPattern = await _db.GuardGroupRotationPatterns
                .Where(gp => gp.GroupId == group.GroupId && gp.IsActive
                    && gp.ValidFrom <= dto.StartDate
                    && (gp.ValidTo == null || gp.ValidTo >= dto.StartDate))
                .OrderByDescending(gp => gp.ValidFrom)
                .FirstOrDefaultAsync(ct);

            if (groupPattern is null) continue;

            var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct);
            if (pattern is null) continue;

            var activeEmployees = await _groupRepo.GetActiveEmployeesAsync(group.GroupId, dto.StartDate, ct);
            if (!activeEmployees.Any()) continue;

            for (var date = dto.StartDate; date <= dto.EndDate; date = date.AddDays(1))
            {
                int cyclePos = ((date.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays;
                int cycleDay = cyclePos + 1;
                var patternDetail = pattern.Details.FirstOrDefault(d => d.DayOrder == cycleDay);

                if (patternDetail is null || patternDetail.IsRestDay)
                {
                    restDays += activeEmployees.Count;
                    if (dto.IncludeRestDays)
                    {
                        foreach (var emp in activeEmployees)
                            items.Add(MakePreviewItem(emp, group, dto.LocationId, locationName, date, 0, null, "Libre", cycleDay, false, false, null, null, true, true));
                    }
                    continue;
                }

                if (!patternDetail.ScheduleId.HasValue) continue;
                scheduleMap.TryGetValue(patternDetail.ScheduleId.Value, out var schedule);

                foreach (var emp in activeEmployees)
                {
                    if (dto.EmployeeId.HasValue && emp.EmployeeId != dto.EmployeeId) continue;

                    var hasExisting = await _repo.HasActiveShiftOnDateAsync(emp.EmployeeId, date, null, ct);
                    bool willSkip = hasExisting && dto.RegenerateMode != "CANCEL_AND_RECREATE";

                    // Cancelar existente si modo CANCEL_AND_RECREATE y no es dry run
                    if (hasExisting && !dryRun && dto.RegenerateMode == "CANCEL_AND_RECREATE")
                    {
                        var existing = await _db.GuardShiftPlannings
                            .FirstOrDefaultAsync(p => p.EmployeeId == emp.EmployeeId && p.WorkDate == date && p.IsActiveForAssignment, ct);
                        if (existing is not null) existing.IsActiveForAssignment = false;
                        willSkip = false;
                    }

                    // Validar conflictos
                    string? conflictType = null;
                    string? conflictMessage = null;
                    bool hasConflict = false;

                    if (!willSkip)
                    {
                        var validateReq = new ValidateGuardAssignmentRequestDto(
                            emp.EmployeeId, dto.LocationId ?? 0, date, patternDetail.ScheduleId.Value, null, false);
                        var validation = await _validationService.ValidateAsync(validateReq, ct);

                        if (!validation.CanAssign)
                        {
                            hasConflict = true;
                            var blocking = validation.Validations.FirstOrDefault(v => v.Severity == "BLOCKING" && v.Result == "FAILED");
                            conflictType = blocking?.ValidationType;
                            conflictMessage = blocking?.Message;
                        }
                    }

                    // Agregar a planificación si no hay conflicto, no se omite y es confirm
                    if (!dryRun && !willSkip && !hasConflict && dto.LocationId.HasValue)
                    {
                        var planning = new WsUtaSystem.Models.Guards.GuardShiftPlanning
                        {
                            EmployeeId = emp.EmployeeId,
                            GroupId = group.GroupId,
                            LocationId = dto.LocationId.Value,
                            WorkDate = date,
                            ScheduleId = patternDetail.ScheduleId.Value,
                            PlanningSourceTypeId = sourceTypeId,
                            StatusTypeId = statusTypeId,
                            IsAutoGenerated = true,
                            IsActiveForAssignment = true
                        };
                        await _db.GuardShiftPlannings.AddAsync(planning, ct);
                    }

                    var empName = $"{emp.Employee?.People?.FirstName} {emp.Employee?.People?.LastName}".Trim();
                    if (string.IsNullOrWhiteSpace(empName)) empName = emp.EmployeeId.ToString();

                    items.Add(MakePreviewItem(
                        emp, group, dto.LocationId, locationName, date,
                        patternDetail.ScheduleId.Value,
                        schedule?.ScheduleCode, schedule?.Description ?? "",
                        cycleDay, willSkip, hasConflict, conflictType, conflictMessage,
                        !hasConflict && !willSkip, false));
                }
            }
        }

        return (items, restDays);
    }

    private static GeneratePreviewItemDto MakePreviewItem(
        WsUtaSystem.Models.Guards.GuardRotationGroupEmployee emp,
        WsUtaSystem.Models.Guards.GuardRotationGroup group,
        int? locationId, string? locationName,
        DateOnly date, int scheduleId,
        string? scheduleCode, string scheduleName,
        int cycleDay, bool willSkip, bool hasConflict,
        string? conflictType, string? conflictMessage,
        bool isValid, bool isRestDay)
    {
        var empName = $"{emp.Employee?.People?.FirstName} {emp.Employee?.People?.LastName}".Trim();
        if (string.IsNullOrWhiteSpace(empName)) empName = emp.EmployeeId.ToString();

        return new GeneratePreviewItemDto(
            emp.EmployeeId, empName,
            group.GroupId, group.Name,
            locationId, locationName,
            date, scheduleId, scheduleCode, scheduleName,
            cycleDay, willSkip, hasConflict, conflictType, conflictMessage,
            isValid, isRestDay
        );
    }

    private async Task<List<WsUtaSystem.Models.Guards.GuardRotationGroup>> ResolveGroupsAsync(
        GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var query = _db.Set<WsUtaSystem.Models.Guards.GuardRotationGroup>()
            .Where(g => g.IsActive);

        if (dto.Mode == "BY_GROUP" && dto.GroupId.HasValue)
            query = query.Where(g => g.GroupId == dto.GroupId.Value);

        return await query.ToListAsync(ct);
    }

    private static GeneratePreviewResponseDto BuildPreviewResponse(List<GeneratePreviewItemDto> items, int restDays) =>
        new(
            items.Count(i => i.IsValid && !i.WillSkip),
            restDays,
            items.Count(i => i.WillSkip),
            items.Count(i => i.HasConflict),
            items.Count(i => i.ConflictType == "PERMISSION_CONFLICT"),
            items.Count(i => i.ConflictType == "VACATION_CONFLICT"),
            items.Count(i => i.ConflictType == "DOUBLE_SHIFT"),
            items.Count(i => i.ConflictType == "OVERLAP"),
            items.Count(i => !i.LocationId.HasValue && !i.IsRestDay),
            items
        );
}
