using Microsoft.EntityFrameworkCore;
using WsUtaSystem.Application.Common.Extensions;
using WsUtaSystem.Application.Common.Interfaces;
using WsUtaSystem.Application.DTOs.Guards;
using WsUtaSystem.Application.Interfaces.Guards;
using WsUtaSystem.Data;
using WsUtaSystem.Models;
using WsUtaSystem.Models.Guards;

namespace WsUtaSystem.Application.Services.Guards;

public class GuardShiftPlanningService : IGuardShiftPlanningService
{
    private readonly IGuardShiftPlanningRepository _repo;
    private readonly IGuardAssignmentValidationService _validationService;
    private readonly IEmployeeAvailabilityService _availabilityService;
    private readonly IGuardRotationGroupRepository _groupRepo;
    private readonly IRotationPatternRepository _patternRepo;
    private readonly AppDbContext _db;
    private readonly ICurrentUserService _currentUser;

    public GuardShiftPlanningService(
        IGuardShiftPlanningRepository repo,
        IGuardAssignmentValidationService validationService,
        IEmployeeAvailabilityService availabilityService,
        IGuardRotationGroupRepository groupRepo,
        IRotationPatternRepository patternRepo,
        AppDbContext db,
        ICurrentUserService currentUser)
    {
        _repo = repo;
        _validationService = validationService;
        _availabilityService = availabilityService;
        _groupRepo = groupRepo;
        _patternRepo = patternRepo;
        _db = db;
        _currentUser = currentUser;
    }

    public async Task<List<GuardShiftCalendarItemDto>> GetCalendarAsync(GuardShiftCalendarFilterDto filter, CancellationToken ct)
    {
        var plannings = await _repo.GetCalendarAsync(filter, ct);

        return plannings.Select(p =>
        {
            var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
            return new GuardShiftCalendarItemDto(
                p.WorkDate, p.PlanningId, p.EmployeeId,
                p.Employee?.People.GetFullName() ?? string.Empty,
                p.LocationId, p.Location?.LocationName ?? "",
                p.ScheduleId, p.Schedule?.Description ?? "",
                p.Schedule?.ScheduleCode,
                p.StatusType?.Name ?? "",
                activeChange is not null,
                false, false, false
            );
        }).ToList();
    }

    public async Task<GuardShiftPlanningDto?> GetByIdAsync(int planningId, CancellationToken ct)
    {
        var p = await _repo.GetWithChangesAsync(planningId, ct);
        if (p is null) return null;
        return MapToDto(p);
    }

    public async Task<GuardShiftPlanningDto> CreateAsync(CreateGuardShiftPlanningDto dto, CancellationToken ct)
    {
        var validateReq = new ValidateGuardAssignmentRequestDto(
            dto.EmployeeId, dto.LocationId, dto.WorkDate, dto.ScheduleId, null, false);
        var validation = await _validationService.ValidateAsync(validateReq, ct);

        if (validation.HasBlockingErrors)
            throw new InvalidOperationException(
                "No se puede crear la planificación: " +
                string.Join("; ", validation.Validations.Where(v => v.Severity == "BLOCKING").Select(v => v.Message)));

        var isSpecialGroup = dto.GroupId.HasValue
            && await _db.GuardRotationGroups.Where(g => g.GroupId == dto.GroupId).Select(g => g.IsSpecial).FirstOrDefaultAsync(ct);

        var entity = new GuardShiftPlanning
        {
            EmployeeId = dto.EmployeeId,
            GroupId = dto.GroupId,
            LocationId = dto.LocationId,
            WorkDate = dto.WorkDate,
            ScheduleId = dto.ScheduleId,
            PlanningSourceTypeId = dto.PlanningSourceTypeId,
            StatusTypeId = dto.StatusTypeId,
            IsAutoGenerated = false,
            IsActiveForAssignment = true,
            AllowDoubleShift = isSpecialGroup,
            Notes = dto.Notes
        };
        await _db.GuardShiftPlannings.AddAsync(entity, ct);
        await _db.SaveChangesAsync(ct);
        return MapToDto(entity);
    }

    public async Task<GuardShiftPlanningResultDto> GenerateAsync(GenerateGuardShiftPlanningRequestDto dto, CancellationToken ct)
    {
        var group = await _groupRepo.GetWithEmployeesAsync(dto.GroupId, ct)
            ?? throw new KeyNotFoundException($"Grupo {dto.GroupId} no encontrado.");

        var groupPattern = await _db.GuardGroupRotationPatterns
            .Where(gp => gp.GroupId == dto.GroupId && gp.IsActive
                && gp.ValidFrom <= dto.StartDate
                && (gp.ValidTo == null || gp.ValidTo >= dto.StartDate))
            .OrderByDescending(gp => gp.ValidFrom)
            .FirstOrDefaultAsync(ct)
            ?? throw new InvalidOperationException($"El grupo {dto.GroupId} no tiene patrón de rotación activo para la fecha indicada.");

        var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct)
            ?? throw new KeyNotFoundException($"Patrón {groupPattern.PatternId} no encontrado.");

        var sourceTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_SOURCE" && r.Name == "AUTO")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        var statusTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_STATUS" && r.Name == "PLANNED")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        int generated = 0, skipped = 0, errors = 0;
        var messages = new List<string>();
        var activeEmployees = await _groupRepo.GetActiveEmployeesAsync(dto.GroupId, dto.StartDate, ct);

        for (var date = dto.StartDate; date <= dto.EndDate; date = date.AddDays(1))
        {
            int cycleDay = ((date.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays;
            var patternDetail = pattern.Details.FirstOrDefault(d => d.DayOrder == cycleDay + 1);
            if (patternDetail is null || patternDetail.IsRestDay) continue;

            foreach (var groupEmp in activeEmployees)
            {
                try
                {
                    var hasShift = await _repo.HasActiveShiftOnDateAsync(groupEmp.EmployeeId, date, null, ct);
                    if (hasShift && !group.IsSpecial)
                    {
                        if (!dto.OverwriteExisting) { skipped++; continue; }
                        var existing = await _db.GuardShiftPlannings
                            .FirstAsync(p => p.EmployeeId == groupEmp.EmployeeId && p.WorkDate == date && p.IsActiveForAssignment, ct);
                        existing.IsActiveForAssignment = false;
                    }

                    var planning = new GuardShiftPlanning
                    {
                        EmployeeId = groupEmp.EmployeeId,
                        GroupId = dto.GroupId,
                        LocationId = dto.LocationId,
                        WorkDate = date,
                        ScheduleId = patternDetail.ScheduleId!.Value,
                        PlanningSourceTypeId = sourceTypeId,
                        StatusTypeId = statusTypeId,
                        IsAutoGenerated = true,
                        IsActiveForAssignment = true,
                        AllowDoubleShift = group.IsSpecial
                    };

                    await _db.GuardShiftPlannings.AddAsync(planning, ct);
                    generated++;
                }
                catch (Exception ex)
                {
                    errors++;
                    messages.Add($"Error en empleado {groupEmp.EmployeeId} fecha {date}: {ex.Message}");
                }
            }
        }

        await _db.SaveChangesAsync(ct);
        messages.Insert(0, $"Generación completada: {generated} creados, {skipped} omitidos, {errors} errores.");
        return new GuardShiftPlanningResultDto(generated, skipped, errors, messages);
    }

    public async Task<GuardShiftPlanningDetailDto?> GetPlanningDetailAsync(int planningId, CancellationToken ct)
    {
        var p = await _db.GuardShiftPlannings
            .Include(x => x.Employee).ThenInclude(e => e!.People)
            .Include(x => x.Location)
            .Include(x => x.Schedule)
            .Include(x => x.StatusType)
            .Include(x => x.Changes).ThenInclude(c => c.ReplacementEmployee).ThenInclude(e => e!.People)
            .Include(x => x.Changes).ThenInclude(c => c.OriginalSchedule)
            .Include(x => x.Changes).ThenInclude(c => c.NewSchedule)
            .Include(x => x.Changes).ThenInclude(c => c.NewLocation)
            .Include(x => x.Changes).ThenInclude(c => c.ChangeType)
            .Include(x => x.Changes).ThenInclude(c => c.StatusType)
            .Include(x => x.Validations).ThenInclude(v => v.ValidationType)
            .Include(x => x.Validations).ThenInclude(v => v.ResultType)
            .Include(x => x.Validations).ThenInclude(v => v.SeverityType)
            .FirstOrDefaultAsync(x => x.PlanningId == planningId, ct);

        if (p is null) return null;

        // Resolver patrón del grupo para calcular día de ciclo
        int? cycleDay = null;
        int? patternId = null;
        string? patternCode = null;
        string? patternSequence = null;

        if (p.GroupId.HasValue)
        {
            var groupPattern = await _db.GuardGroupRotationPatterns
                .Where(gp => gp.GroupId == p.GroupId && gp.IsActive
                    && gp.ValidFrom <= p.WorkDate
                    && (gp.ValidTo == null || gp.ValidTo >= p.WorkDate))
                .OrderByDescending(gp => gp.ValidFrom)
                .FirstOrDefaultAsync(ct);

            if (groupPattern is not null)
            {
                patternId = groupPattern.PatternId;
                var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct);
                if (pattern is not null)
                {
                    patternCode = pattern.PatternCode;
                    cycleDay = ((p.WorkDate.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays + 1;
                    patternSequence = string.Join("", pattern.Details
                        .OrderBy(d => d.DayOrder)
                        .Select(d => d.IsRestDay ? "L" : (d.Schedule?.ScheduleCode?.Substring(0, 1) ?? "?")));
                }
            }
        }

        var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
        var validations = p.Validations.Select(v => new GuardAssignmentValidationDto(
            v.ValidationId, v.EmployeeId,
            p.Employee?.People.GetFullName() ?? string.Empty,
            v.PlanningId, v.ShiftChangeId,
            v.ValidationType?.Name ?? "", v.ResultType?.Name ?? "", v.SeverityType?.Name ?? "",
            v.ValidationDate, v.Message, v.Details
        )).ToList();

        var changes = p.Changes.Select(MapChangeToDto).ToList();

        return new GuardShiftPlanningDetailDto(
            p.PlanningId, p.WorkDate,
            p.LocationId, p.Location?.LocationName ?? "", p.Location?.LocationCode,
            p.GroupId, null,
            patternId, patternCode, patternSequence, cycleDay,
            p.ScheduleId, p.Schedule?.ScheduleCode, p.Schedule?.Description ?? "",
            p.EmployeeId, p.Employee?.People.GetFullName() ?? string.Empty, p.Employee?.People?.IdCard,
            p.StatusType?.Name ?? "", p.IsAutoGenerated, p.Notes,
            activeChange is not null,
            activeChange?.ReplacementEmployeeId,
            activeChange is not null ? activeChange.ReplacementEmployee?.People.GetFullName() : null,
            validations, changes
        );
    }

    public async Task<GeneratePreviewResponseDto> GeneratePreviewAsync(GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var today = DateOnly.FromDateTime(DateTime.Today);
        if (dto.StartDate < today)
            throw new InvalidOperationException($"No se puede generar planificación para fechas pasadas. La fecha de inicio debe ser {today:dd/MM/yyyy} o posterior.");

        var (items, restDays) = await RunGenerationLogicAsync(dto, dryRun: true, ct);
        return BuildPreviewResponse(items, restDays);
    }

    public async Task<GuardShiftPlanningResultDto> GenerateConfirmAsync(GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var today = DateOnly.FromDateTime(DateTime.Today);
        if (dto.StartDate < today)
            throw new InvalidOperationException($"No se puede generar planificación para fechas pasadas. La fecha de inicio debe ser {today:dd/MM/yyyy} o posterior.");

        var (items, _) = await RunGenerationLogicAsync(dto, dryRun: false, ct);
        await _db.SaveChangesAsync(ct);

        var generated = items.Count(i => i.IsValid && !i.WillSkip);
        var skipped   = items.Count(i => i.WillSkip);
        var errors    = items.Count(i => i.HasConflict);

        var messages = new List<string> { $"Generación confirmada: {generated} creados, {skipped} omitidos, {errors} conflictos." };
        foreach (var conflict in items.Where(i => i.HasConflict).Take(20))
            messages.Add($"  Conflicto [{conflict.ConflictType}] {conflict.EmployeeFullName} {conflict.WorkDate:dd/MM/yyyy}: {conflict.ConflictMessage}");

        return new GuardShiftPlanningResultDto(generated, skipped, errors, messages);
    }

    public async Task<ScheduleBoardResponseDto> GetScheduleBoardAsync(ScheduleBoardFilterDto filter, CancellationToken ct)
    {
        var query = _db.GuardShiftPlannings
            .Include(p => p.Employee).ThenInclude(e => e!.People)
            .Include(p => p.Location).ThenInclude(l => l!.Parent)
            .Include(p => p.Schedule)
            .Include(p => p.StatusType)
            .Include(p => p.Group)
            .Include(p => p.Changes.Where(c => c.IsActiveForAttendance))
            .Where(p => p.WorkDate >= filter.StartDate
                     && p.WorkDate <= filter.EndDate
                     && p.IsActiveForAssignment);

        if (filter.LocationId.HasValue)     query = query.Where(p => p.LocationId == filter.LocationId);
        if (filter.GroupId.HasValue)        query = query.Where(p => p.GroupId == filter.GroupId);
        if (filter.EmployeeId.HasValue)     query = query.Where(p => p.EmployeeId == filter.EmployeeId);
        if (!string.IsNullOrEmpty(filter.Status))       query = query.Where(p => p.StatusType!.Name == filter.Status);
        if (!string.IsNullOrEmpty(filter.ScheduleCode)) query = query.Where(p => p.Schedule!.ScheduleCode == filter.ScheduleCode);

        var plannings = await query.ToListAsync(ct);

        var dates = new List<DateOnly>();
        for (var d = filter.StartDate; d <= filter.EndDate; d = d.AddDays(1))
            dates.Add(d);

        // Cargar asignaciones individuales de sub-ubicación para los empleados en el tablero
        var employeeIds = plannings.Select(p => p.EmployeeId).Distinct().ToList();
        var empSubLocations = await _db.Set<GuardLocationRotationAssignment>()
            .Include(a => a.Location).ThenInclude(l => l!.Parent)
            .Include(a => a.Period)
            .Where(a => a.EmployeeId != null
                     && employeeIds.Contains(a.EmployeeId!.Value)
                     && a.IsActive
                     && a.Period!.StartDate <= filter.EndDate
                     && a.Period.EndDate >= filter.StartDate)
            .ToListAsync(ct);

        // Prioridad: asignación individual más reciente por empleado
        var empLocationLookup = empSubLocations
            .GroupBy(a => a.EmployeeId!.Value)
            .ToDictionary(
                g => g.Key,
                g => g.OrderByDescending(a => a.Period!.StartDate).First()
            );

        // Función para resolver la ubicación efectiva de un planning (sub-ubicación o la del planning)
        (int id, string name, string? code, int? parentId, string? parentName) EffectiveLocation(GuardShiftPlanning p)
        {
            if (empLocationLookup.TryGetValue(p.EmployeeId, out var empAssign))
                return (empAssign.LocationId, empAssign.Location?.LocationName ?? "", empAssign.Location?.LocationCode,
                        empAssign.Location?.ParentLocationId, empAssign.Location?.Parent?.LocationName);
            return (p.LocationId, p.Location?.LocationName ?? "", p.Location?.LocationCode,
                    p.Location?.ParentLocationId, p.Location?.Parent?.LocationName);
        }

        // Agrupar por ubicación efectiva + turno
        var rowGroups = plannings
            .GroupBy(p => new { EffLoc = EffectiveLocation(p).id, ScheduleCode = p.Schedule?.ScheduleCode ?? "" })
            .OrderBy(g => { var (_, name, _, _, _) = EffectiveLocation(g.First()); return name; })
            .ThenBy(g => g.Key.ScheduleCode);

        var rows = rowGroups.Select(group =>
        {
            var sample = group.First();
            var (locId, locName, locCode, parentLocId, parentLocName) = EffectiveLocation(sample);
            var rowKey = $"{locCode ?? locId.ToString()}_{sample.Schedule?.ScheduleCode ?? "X"}";

            var cells = dates.Select(date =>
            {
                var dayPlannings = group.Where(p => p.WorkDate == date).ToList();
                var employees = dayPlannings.Select(p =>
                {
                    var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
                    return new ScheduleBoardCellEmployeeDto(
                        p.EmployeeId,
                        p.Employee?.People.GetFullName() ?? string.Empty,
                        activeChange is not null,
                        p.PlanningId,
                        p.GroupId,
                        p.Group?.Name,
                        p.Group?.ColorCode
                    );
                }).ToList();

                var cellStatus = dayPlannings.Count == 0 ? "UNCOVERED" : (sample.StatusType?.Name ?? "PLANNED");

                return new ScheduleBoardCellDto(
                    date, dayPlannings.FirstOrDefault()?.PlanningId,
                    employees, cellStatus,
                    false, employees.Any(e => e.IsReplacement), false, false
                );
            }).ToList();

            return new ScheduleBoardRowDto(
                rowKey, locId,
                locName, locCode,
                parentLocId, parentLocName,
                sample.Schedule?.ScheduleCode ?? "", sample.Schedule?.Description ?? "",
                cells
            );
        }).ToList();

        return new ScheduleBoardResponseDto(dates, rows);
    }

    public async Task<ValidateGuardAssignmentResultDto> ValidateAssignmentAsync(ValidateGuardAssignmentRequestDto dto, CancellationToken ct) =>
        await _validationService.ValidateAsync(dto, ct);

    public async Task<GuardDashboardDto> GetDashboardAsync(CancellationToken ct)
    {
        var today = DateOnly.FromDateTime(DateTime.Today);
        var filter = new GuardShiftCalendarFilterDto(today, today, null, null, null, null, null);
        var todayShifts = await GetCalendarAsync(filter, ct);

        var pendingChanges = await _db.GuardShiftChanges
            .Include(c => c.Planning).ThenInclude(p => p!.Location)
            .Include(c => c.OriginalEmployee).ThenInclude(e => e!.People)
            .Include(c => c.ReplacementEmployee).ThenInclude(e => e!.People)
            .Include(c => c.StatusType)
            .Where(c => c.StatusType!.Name == "PENDING")
            .ToListAsync(ct);

        var pendingDtos = pendingChanges.Select(MapChangeToDto).ToList();

        return new GuardDashboardDto(
            todayShifts.Count,
            0,
            pendingDtos.Count,
            0,
            0,
            todayShifts,
            pendingDtos
        );
    }

    private static GuardShiftPlanningDto MapToDto(GuardShiftPlanning p)
    {
        var activeChange = p.Changes.FirstOrDefault(c => c.IsActiveForAttendance);
        return new GuardShiftPlanningDto(
            p.PlanningId, p.EmployeeId,
            p.Employee?.People.GetFullName() ?? string.Empty,
            p.Employee?.People?.IdCard,
            p.GroupId, p.Group?.Name, p.LocationId, p.Location?.LocationName ?? "",
            p.Location?.LocationCode, p.WorkDate, p.ScheduleId,
            p.Schedule?.Description ?? "", p.Schedule?.ScheduleCode,
            p.PlanningSourceType?.Name ?? "", p.StatusType?.Name ?? "",
            p.IsAutoGenerated, p.IsActiveForAssignment, p.Notes,
            activeChange is not null,
            activeChange?.ReplacementEmployeeId,
            activeChange is not null ? activeChange.ReplacementEmployee?.People.GetFullName() : null
        );
    }

    private static GuardShiftChangeDto MapChangeToDto(GuardShiftChange c) =>
        new(c.ShiftChangeId, c.PlanningId,
            c.Planning?.WorkDate ?? default,
            c.OriginalEmployeeId,
            c.OriginalEmployee?.People.GetFullName() ?? string.Empty,
            c.ReplacementEmployeeId,
            c.ReplacementEmployee is null ? null : c.ReplacementEmployee.People.GetFullName(),
            c.OriginalScheduleId, c.OriginalSchedule?.Description ?? "",
            c.NewScheduleId, c.NewSchedule?.Description,
            c.ChangeType?.Name ?? "", c.StatusType?.Name ?? "",
            c.IsActiveForAttendance, c.Reason, c.RequestedAt, c.RequestedBy, null,
            c.ApprovedBy, null, c.ApprovedAt, c.RejectionReason,
            c.NewWorkDate, c.NewLocationId, c.NewLocation?.LocationName);

    public async Task<GuardReadinessCheckDto> GetReadinessCheckAsync(DateOnly targetDate, CancellationToken ct)
    {
        var items = new List<GuardReadinessItemDto>();

        // 1. Existen grupos activos con empleados
        var groupsWithEmployees = await _db.GuardRotationGroups
            .Where(g => g.Employees.Any(ge => ge.IsActive))
            .CountAsync(ct);

        items.Add(new GuardReadinessItemDto(
            "GROUPS_WITH_EMPLOYEES",
            "Grupos con empleados asignados",
            groupsWithEmployees > 0,
            groupsWithEmployees > 0
                ? $"{groupsWithEmployees} grupo(s) con empleados activos."
                : "No hay grupos de rotación con empleados activos."
        ));

        // 2. Grupos activos tienen patrón de rotación para la fecha
        var groupsTotal = await _db.GuardRotationGroups.CountAsync(ct);
        var groupsWithPattern = await _db.GuardGroupRotationPatterns
            .Where(gp => gp.IsActive && gp.ValidFrom <= targetDate && (gp.ValidTo == null || gp.ValidTo >= targetDate))
            .Select(gp => gp.GroupId)
            .Distinct()
            .CountAsync(ct);

        var patternOk = groupsTotal > 0 && groupsWithPattern == groupsTotal;
        items.Add(new GuardReadinessItemDto(
            "GROUPS_WITH_PATTERN",
            "Grupos con patrón de rotación activo",
            patternOk,
            patternOk
                ? $"Todos los grupos ({groupsWithPattern}) tienen patrón activo para la fecha."
                : $"{groupsWithPattern} de {groupsTotal} grupo(s) tienen patrón activo. Asigna patrón a los grupos restantes."
        ));

        // 3. Existe un periodo de rotación de ubicaciones activo que cubra la fecha
        var activePeriod = await _db.GuardLocationRotationPeriods
            .Where(p => p.IsActive && p.StartDate <= targetDate && p.EndDate >= targetDate)
            .FirstOrDefaultAsync(ct);

        items.Add(new GuardReadinessItemDto(
            "ACTIVE_ROTATION_PERIOD",
            "Periodo de rotación de ubicaciones activo",
            activePeriod is not null,
            activePeriod is not null
                ? $"Periodo '{activePeriod.Name}' activo ({activePeriod.StartDate:dd/MM/yyyy} – {activePeriod.EndDate:dd/MM/yyyy})."
                : $"No existe periodo de rotación de ubicaciones que cubra {targetDate:dd/MM/yyyy}. Crea uno en Rotación de Ubicaciones."
        ));

        // 4. Todos los grupos tienen asignación de ubicación en el periodo activo
        // Se considera cubierto si tiene asignación a nivel de grupo O al menos un empleado individual asignado
        if (activePeriod is not null)
        {
            var periodId = activePeriod.LocationRotationPeriodId;

            var groupsWithGroupAssignment = await _db.GuardLocationRotationAssignments
                .Where(a => a.LocationRotationPeriodId == periodId && a.IsActive && a.GroupId != null)
                .Select(a => a.GroupId!.Value)
                .Distinct()
                .ToListAsync(ct);

            var groupsWithEmployeeAssignment = await _db.GuardLocationRotationAssignments
                .Where(a => a.LocationRotationPeriodId == periodId && a.IsActive && a.EmployeeId != null)
                .Join(_db.GuardRotationGroupEmployees.Where(ge => ge.IsActive),
                      a => a.EmployeeId, ge => ge.EmployeeId,
                      (a, ge) => ge.GroupId)
                .Distinct()
                .ToListAsync(ct);

            var assignedGroups = groupsWithGroupAssignment.Union(groupsWithEmployeeAssignment).Distinct().Count();

            var locOk = groupsWithEmployees > 0 && assignedGroups >= groupsWithEmployees;
            items.Add(new GuardReadinessItemDto(
                "GROUPS_WITH_LOCATION",
                "Grupos con ubicación asignada en el periodo",
                locOk,
                locOk
                    ? $"Todos los grupos tienen ubicación asignada en el periodo activo."
                    : $"{assignedGroups} de {groupsWithEmployees} grupo(s) con empleados tienen ubicación asignada. Completa las asignaciones en el periodo '{activePeriod.Name}'."
            ));
        }
        else
        {
            items.Add(new GuardReadinessItemDto(
                "GROUPS_WITH_LOCATION",
                "Grupos con ubicación asignada en el periodo",
                false,
                "Requiere un periodo de rotación activo (ver punto anterior)."
            ));
        }

        var isReady = items.All(i => i.Passed);
        return new GuardReadinessCheckDto(isReady, items);
    }

    // ─── Helpers de generación ──────────────────────────────────────────────

    private async Task<(List<GeneratePreviewItemDto> items, int restDays)> RunGenerationLogicAsync(
        GeneratePreviewRequestDto dto, bool dryRun, CancellationToken ct)
    {
        var groups = await ResolveGroupsAsync(dto, ct);
        var items = new List<GeneratePreviewItemDto>();
        int restDays = 0;

        var sourceTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_SOURCE" && r.Name == "AUTO")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        var statusTypeId = await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_STATUS" && r.Name == "PLANNED")
            .Select(r => r.TypeId).FirstOrDefaultAsync(ct);

        var scheduleMap = await _db.Schedules
            .ToDictionaryAsync(s => s.ScheduleId, s => s, ct);

        // Precarga: periodos de rotación de ubicación activos en el rango
        var locationRotationPeriods = await _db.GuardLocationRotationPeriods
            .Where(p => p.IsActive && p.StartDate <= dto.EndDate && p.EndDate >= dto.StartDate)
            .Include(p => p.Assignments.Where(a => a.IsActive))
                .ThenInclude(a => a.Location)
            .ToListAsync(ct);

        // Nombre de la ubicación solicitada por el usuario (fallback paso 4)
        string? fallbackLocationName = null;
        if (dto.LocationId.HasValue)
        {
            fallbackLocationName = await _db.Set<WsUtaSystem.Models.Guards.GuardServiceLocation>()
                .Where(l => l.LocationId == dto.LocationId)
                .Select(l => l.LocationName)
                .FirstOrDefaultAsync(ct);
        }

        foreach (var group in groups)
        {
            var groupPattern = await _db.GuardGroupRotationPatterns
                .Where(gp => gp.GroupId == group.GroupId && gp.IsActive
                    && gp.ValidFrom <= dto.StartDate
                    && (gp.ValidTo == null || gp.ValidTo >= dto.StartDate))
                .OrderByDescending(gp => gp.ValidFrom)
                .FirstOrDefaultAsync(ct);

            if (groupPattern is null) continue;

            var pattern = await _patternRepo.GetWithDetailsAsync(groupPattern.PatternId, ct);
            if (pattern is null) continue;

            var activeEmployees = await _groupRepo.GetActiveEmployeesAsync(group.GroupId, dto.StartDate, ct);
            if (!activeEmployees.Any()) continue;

            // Precarga: condiciones especiales de empleados del grupo válidas en el rango
            var empIds = activeEmployees.Select(e => e.EmployeeId).ToList();
            var specialRules = await _db.GuardEmployeeSpecialRules
                .Where(r => r.IsActive && empIds.Contains(r.EmployeeId)
                    && r.ValidFrom <= dto.EndDate && (r.ValidTo == null || r.ValidTo >= dto.StartDate))
                .Include(r => r.FixedLocation)
                .Include(r => r.FixedSchedule)
                .ToListAsync(ct);

            for (var date = dto.StartDate; date <= dto.EndDate; date = date.AddDays(1))
            {
                int cyclePos = ((date.DayNumber - groupPattern.StartCycleDate.DayNumber) % pattern.CycleDays + pattern.CycleDays) % pattern.CycleDays;
                int cycleDay = cyclePos + 1;
                var patternDetail = pattern.Details.FirstOrDefault(d => d.DayOrder == cycleDay);

                if (patternDetail is null || patternDetail.IsRestDay)
                {
                    restDays += activeEmployees.Count;
                    if (dto.IncludeRestDays)
                    {
                        foreach (var emp in activeEmployees)
                            items.Add(MakePreviewItem(emp, group, null, null, date, 0, null, "Libre", cycleDay, false, false, null, null, true, true));
                    }
                    continue;
                }

                if (!patternDetail.ScheduleId.HasValue) continue;

                foreach (var emp in activeEmployees)
                {
                    if (dto.EmployeeId.HasValue && emp.EmployeeId != dto.EmployeeId) continue;

                    // Condición especial activa del empleado en esta fecha
                    var rule = specialRules
                        .Where(r => r.EmployeeId == emp.EmployeeId
                            && r.ValidFrom <= date && (r.ValidTo == null || r.ValidTo >= date))
                        .OrderByDescending(r => r.ValidFrom)
                        .FirstOrDefault();

                    // Solo días hábiles: omitir fin de semana si la regla lo requiere
                    if (rule?.OnlyWeekDays == true &&
                        (date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday))
                    {
                        restDays++;
                        if (dto.IncludeRestDays)
                            items.Add(MakePreviewItem(emp, group, null, null, date, 0, null, "Libre (fin de semana)", cycleDay, false, false, null, null, true, true));
                        continue;
                    }

                    // Horario efectivo: FixedScheduleId de condición especial sobreescribe patrón
                    var effectiveScheduleId = rule?.FixedScheduleId ?? patternDetail.ScheduleId.Value;
                    scheduleMap.TryGetValue(effectiveScheduleId, out var schedule);

                    // Sin turno nocturno: omitir si la regla lo prohíbe
                    if (rule?.NoNightShift == true && IsNightSchedule(schedule))
                    {
                        restDays++;
                        if (dto.IncludeRestDays)
                            items.Add(MakePreviewItem(emp, group, null, null, date, 0, null, "Libre (sin noche)", cycleDay, false, false, null, null, true, true));
                        continue;
                    }

                    // ── Resolución de ubicación (5 pasos) ────────────────────
                    int? resolvedLocationId;
                    string? resolvedLocationName;

                    if (rule?.FixedLocationId is not null)
                    {
                        // Paso 1: ubicación fija en condición especial del empleado
                        resolvedLocationId = rule.FixedLocationId;
                        resolvedLocationName = rule.FixedLocation?.LocationName;
                    }
                    else
                    {
                        // Pasos 2 y 3: rotación de ubicación (empleado > grupo)
                        (resolvedLocationId, resolvedLocationName) =
                            ResolveLocationFromRotationPeriods(locationRotationPeriods, group.GroupId, emp.EmployeeId, date);
                    }

                    if (resolvedLocationId is null)
                    {
                        // Paso 4: fallback explícito dto.LocationId
                        resolvedLocationId = dto.LocationId;
                        resolvedLocationName = fallbackLocationName;
                    }

                    if (resolvedLocationId is null)
                    {
                        // Paso 5: sin ubicación → conflicto MISSING_LOCATION
                        items.Add(MakePreviewItem(
                            emp, group, null, null, date,
                            effectiveScheduleId, schedule?.ScheduleCode, schedule?.Description ?? "",
                            cycleDay, false, true, "MISSING_LOCATION",
                            "No se encontró ubicación para el empleado en esta fecha.", false, false));
                        continue;
                    }

                    var hasExisting = await _repo.HasActiveShiftOnDateAsync(emp.EmployeeId, date, null, ct);
                    bool willSkip = hasExisting && !group.IsSpecial && dto.RegenerateMode != "CANCEL_AND_RECREATE";

                    if (hasExisting && !dryRun && dto.RegenerateMode == "CANCEL_AND_RECREATE")
                    {
                        var existing = await _db.GuardShiftPlannings
                            .FirstOrDefaultAsync(p => p.EmployeeId == emp.EmployeeId && p.WorkDate == date && p.IsActiveForAssignment, ct);
                        if (existing is not null) existing.IsActiveForAssignment = false;
                        willSkip = false;
                    }

                    string? conflictType = null;
                    string? conflictMessage = null;
                    bool hasConflict = false;

                    if (!willSkip)
                    {
                        var validateReq = new ValidateGuardAssignmentRequestDto(
                            emp.EmployeeId, resolvedLocationId.Value, date, effectiveScheduleId, null, false);
                        var validation = await _validationService.ValidateAsync(validateReq, ct);

                        if (!validation.CanAssign)
                        {
                            hasConflict = true;
                            var blocking = validation.Validations.FirstOrDefault(v => v.Severity == "BLOCKING" && v.Result == "FAILED");
                            conflictType = blocking?.ValidationType;
                            conflictMessage = blocking?.Message;
                        }
                    }

                    if (!dryRun && !willSkip && !hasConflict)
                    {
                        var planning = new WsUtaSystem.Models.Guards.GuardShiftPlanning
                        {
                            EmployeeId = emp.EmployeeId,
                            GroupId = group.GroupId,
                            LocationId = resolvedLocationId.Value,
                            WorkDate = date,
                            ScheduleId = effectiveScheduleId,
                            PlanningSourceTypeId = sourceTypeId,
                            StatusTypeId = statusTypeId,
                            IsAutoGenerated = true,
                            IsActiveForAssignment = true,
                            AllowDoubleShift = group.IsSpecial
                        };
                        await _db.GuardShiftPlannings.AddAsync(planning, ct);
                    }

                    items.Add(MakePreviewItem(
                        emp, group, resolvedLocationId, resolvedLocationName, date,
                        effectiveScheduleId, schedule?.ScheduleCode, schedule?.Description ?? "",
                        cycleDay, willSkip, hasConflict, conflictType, conflictMessage,
                        !hasConflict && !willSkip, false));
                }
            }
        }

        return (items, restDays);
    }

    private static GeneratePreviewItemDto MakePreviewItem(
        WsUtaSystem.Models.Guards.GuardRotationGroupEmployee emp,
        WsUtaSystem.Models.Guards.GuardRotationGroup group,
        int? locationId, string? locationName,
        DateOnly date, int scheduleId,
        string? scheduleCode, string scheduleName,
        int cycleDay, bool willSkip, bool hasConflict,
        string? conflictType, string? conflictMessage,
        bool isValid, bool isRestDay)
    {
        var empName = emp.Employee?.People.GetFullName() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(empName)) empName = emp.EmployeeId.ToString();

        return new GeneratePreviewItemDto(
            emp.EmployeeId, empName,
            group.GroupId, group.Name,
            locationId, locationName,
            date, scheduleId, scheduleCode, scheduleName,
            cycleDay, willSkip, hasConflict, conflictType, conflictMessage,
            isValid, isRestDay
        );
    }

    private async Task<List<WsUtaSystem.Models.Guards.GuardRotationGroup>> ResolveGroupsAsync(
        GeneratePreviewRequestDto dto, CancellationToken ct)
    {
        var query = _db.Set<WsUtaSystem.Models.Guards.GuardRotationGroup>()
            .Where(g => g.IsActive);

        if (dto.Mode == "BY_GROUP" && dto.GroupId.HasValue)
            query = query.Where(g => g.GroupId == dto.GroupId.Value);
        else if (dto.Mode == "BY_EMPLOYEE" && dto.EmployeeId.HasValue)
            query = query.Where(g => g.Employees.Any(e => e.EmployeeId == dto.EmployeeId && e.IsActive));
        else if (dto.Mode == "BY_LOCATION" && dto.LocationId.HasValue)
        {
            var groupIdsForLocation = await _db.GuardLocationRotationAssignments
                .Where(a => a.IsActive && a.LocationId == dto.LocationId && a.GroupId != null
                    && a.Period!.IsActive
                    && a.Period.StartDate <= dto.EndDate
                    && a.Period.EndDate >= dto.StartDate)
                .Select(a => a.GroupId!.Value)
                .Distinct()
                .ToListAsync(ct);
            query = query.Where(g => groupIdsForLocation.Contains(g.GroupId));
        }

        return await query.ToListAsync(ct);
    }

    private static GeneratePreviewResponseDto BuildPreviewResponse(List<GeneratePreviewItemDto> items, int restDays) =>
        new(
            items.Count(i => i.IsValid && !i.WillSkip),
            restDays,
            items.Count(i => i.WillSkip),
            items.Count(i => i.HasConflict),
            items.Count(i => i.ConflictType == "PERMISSION_CONFLICT"),
            items.Count(i => i.ConflictType == "VACATION_CONFLICT"),
            items.Count(i => i.ConflictType == "DOUBLE_SHIFT"),
            items.Count(i => i.ConflictType == "OVERLAP"),
            items.Count(i => i.ConflictType == "MISSING_LOCATION"),
            items
        );

    // Resuelve la ubicación de un empleado/grupo en una fecha usando los periodos de rotación precargados.
    // Prioridad: asignación individual del empleado > asignación del grupo.
    private static (int? locationId, string? locationName) ResolveLocationFromRotationPeriods(
        List<WsUtaSystem.Models.Guards.GuardLocationRotationPeriod> periods,
        int groupId, int employeeId, DateOnly date)
    {
        var activePeriodAssignments = periods
            .Where(p => p.StartDate <= date && p.EndDate >= date)
            .SelectMany(p => p.Assignments)
            .ToList();

        var empAssignment = activePeriodAssignments
            .FirstOrDefault(a => a.EmployeeId == employeeId);
        if (empAssignment is not null)
            return (empAssignment.LocationId, empAssignment.Location?.LocationName);

        var groupAssignment = activePeriodAssignments
            .FirstOrDefault(a => a.GroupId == groupId);
        if (groupAssignment is not null)
            return (groupAssignment.LocationId, groupAssignment.Location?.LocationName);

        return (null, null);
    }

    // Determina si un horario corresponde a turno nocturno.
    // Usa el primer carácter del código (N=Noche) o la hora de entrada como fallback.
    private static bool IsNightSchedule(Schedules? schedule)
    {
        if (schedule is null) return false;
        if (!string.IsNullOrEmpty(schedule.ScheduleCode))
            return schedule.ScheduleCode.StartsWith("N", StringComparison.OrdinalIgnoreCase);
        var hour = schedule.EntryTime.Hour;
        return hour >= 20 || hour < 6;
    }

    // ── Cancelación de planificación ────────────────────────────────────────
    // No borra filas: marca IsActiveForAssignment=false (mismo flag que ya usa
    // GenerateAsync al sobrescribir con OverwriteExisting — ver línea ~139),
    // por lo que HasActiveShiftOnDateAsync libera la fecha automáticamente
    // sin tocar esa lógica ni el chequeo de "ya planificado".

    private async Task<int> GetCancelledStatusTypeIdAsync(CancellationToken ct) =>
        await _db.Set<RefTypes>()
            .Where(r => r.Category == "GUARD_PLANNING_STATUS" && r.Name == "CANCELLED")
            .Select(r => r.TypeId)
            .FirstOrDefaultAsync(ct);

    public async Task<GuardShiftPlanningDto> CancelPlanningAsync(int planningId, CancelGuardShiftPlanningDto dto, CancellationToken ct)
    {
        var planning = await _repo.GetWithChangesAsync(planningId, ct)
            ?? throw new KeyNotFoundException($"Planificación {planningId} no encontrada.");

        if (!planning.IsActiveForAssignment)
            throw new InvalidOperationException("La planificación ya está cancelada.");

        var cancelledStatusId = await GetCancelledStatusTypeIdAsync(ct);
        if (cancelledStatusId == 0)
            throw new InvalidOperationException("No se encontró el estado CANCELLED en HR.ref_Types (Category=GUARD_PLANNING_STATUS).");

        planning.StatusTypeId = cancelledStatusId;
        planning.IsActiveForAssignment = false;
        if (!string.IsNullOrWhiteSpace(dto.Notes))
            planning.Notes = string.IsNullOrWhiteSpace(planning.Notes) ? dto.Notes : $"{planning.Notes} | {dto.Notes}";

        await _db.SaveChangesAsync(ct);

        var updated = await _repo.GetWithChangesAsync(planningId, ct);
        return MapToDto(updated!);
    }

    public async Task<CancelGuardShiftPlanningResultDto> CancelPlanningRangeAsync(CancelGuardShiftPlanningRangeDto dto, CancellationToken ct)
    {
        if (dto.EndDate < dto.StartDate)
            throw new InvalidOperationException("La fecha final no puede ser anterior a la fecha de inicio.");

        var cancelledStatusId = await GetCancelledStatusTypeIdAsync(ct);
        if (cancelledStatusId == 0)
            throw new InvalidOperationException("No se encontró el estado CANCELLED en HR.ref_Types (Category=GUARD_PLANNING_STATUS).");

        var affected = await _db.GuardShiftPlannings
            .Where(p => (dto.GroupId == null || p.GroupId == dto.GroupId)
                     && p.WorkDate >= dto.StartDate && p.WorkDate <= dto.EndDate
                     && p.IsActiveForAssignment)
            .ToListAsync(ct);

        foreach (var p in affected)
        {
            p.StatusTypeId = cancelledStatusId;
            p.IsActiveForAssignment = false;
            if (!string.IsNullOrWhiteSpace(dto.Notes))
                p.Notes = string.IsNullOrWhiteSpace(p.Notes) ? dto.Notes : $"{p.Notes} | {dto.Notes}";
        }

        await _db.SaveChangesAsync(ct);

        var summary = dto.GroupId == null
            ? $"Cancelación completada: {affected.Count} planificaciones canceladas en {affected.Select(p => p.GroupId).Distinct().Count()} grupo(s)."
            : $"Cancelación completada: {affected.Count} planificaciones canceladas.";
        var messages = new List<string> { summary };
        return new CancelGuardShiftPlanningResultDto(affected.Count, messages);
    }
}
